// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.github.aaric.achieve.protobuf;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>bool status = 4;</code>
     */
    boolean getStatus();

    /**
     * <code>repeated .protobuf.Dept depts = 5;</code>
     */
    java.util.List<com.github.aaric.achieve.protobuf.DeptProto.Dept> 
        getDeptsList();
    /**
     * <code>repeated .protobuf.Dept depts = 5;</code>
     */
    com.github.aaric.achieve.protobuf.DeptProto.Dept getDepts(int index);
    /**
     * <code>repeated .protobuf.Dept depts = 5;</code>
     */
    int getDeptsCount();
    /**
     * <code>repeated .protobuf.Dept depts = 5;</code>
     */
    java.util.List<? extends com.github.aaric.achieve.protobuf.DeptProto.DeptOrBuilder> 
        getDeptsOrBuilderList();
    /**
     * <code>repeated .protobuf.Dept depts = 5;</code>
     */
    com.github.aaric.achieve.protobuf.DeptProto.DeptOrBuilder getDeptsOrBuilder(
        int index);

    /**
     * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
     */
    boolean hasLastLoginTime();
    /**
     * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
     */
    com.google.protobuf.Timestamp getLastLoginTime();
    /**
     * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getLastLoginTimeOrBuilder();
  }
  /**
   * Protobuf type {@code protobuf.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      id_ = 0;
      username_ = "";
      password_ = "";
      status_ = false;
      depts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 32: {

              status_ = input.readBool();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                depts_ = new java.util.ArrayList<com.github.aaric.achieve.protobuf.DeptProto.Dept>();
                mutable_bitField0_ |= 0x00000010;
              }
              depts_.add(
                  input.readMessage(com.github.aaric.achieve.protobuf.DeptProto.Dept.parser(), extensionRegistry));
              break;
            }
            case 50: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (lastLoginTime_ != null) {
                subBuilder = lastLoginTime_.toBuilder();
              }
              lastLoginTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lastLoginTime_);
                lastLoginTime_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          depts_ = java.util.Collections.unmodifiableList(depts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.aaric.achieve.protobuf.UserProto.internal_static_protobuf_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.aaric.achieve.protobuf.UserProto.internal_static_protobuf_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.aaric.achieve.protobuf.UserProto.User.class, com.github.aaric.achieve.protobuf.UserProto.User.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object username_;
    /**
     * <code>string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private boolean status_;
    /**
     * <code>bool status = 4;</code>
     */
    public boolean getStatus() {
      return status_;
    }

    public static final int DEPTS_FIELD_NUMBER = 5;
    private java.util.List<com.github.aaric.achieve.protobuf.DeptProto.Dept> depts_;
    /**
     * <code>repeated .protobuf.Dept depts = 5;</code>
     */
    public java.util.List<com.github.aaric.achieve.protobuf.DeptProto.Dept> getDeptsList() {
      return depts_;
    }
    /**
     * <code>repeated .protobuf.Dept depts = 5;</code>
     */
    public java.util.List<? extends com.github.aaric.achieve.protobuf.DeptProto.DeptOrBuilder> 
        getDeptsOrBuilderList() {
      return depts_;
    }
    /**
     * <code>repeated .protobuf.Dept depts = 5;</code>
     */
    public int getDeptsCount() {
      return depts_.size();
    }
    /**
     * <code>repeated .protobuf.Dept depts = 5;</code>
     */
    public com.github.aaric.achieve.protobuf.DeptProto.Dept getDepts(int index) {
      return depts_.get(index);
    }
    /**
     * <code>repeated .protobuf.Dept depts = 5;</code>
     */
    public com.github.aaric.achieve.protobuf.DeptProto.DeptOrBuilder getDeptsOrBuilder(
        int index) {
      return depts_.get(index);
    }

    public static final int LASTLOGINTIME_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp lastLoginTime_;
    /**
     * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
     */
    public boolean hasLastLoginTime() {
      return lastLoginTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
     */
    public com.google.protobuf.Timestamp getLastLoginTime() {
      return lastLoginTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastLoginTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastLoginTimeOrBuilder() {
      return getLastLoginTime();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
      }
      if (status_ != false) {
        output.writeBool(4, status_);
      }
      for (int i = 0; i < depts_.size(); i++) {
        output.writeMessage(5, depts_.get(i));
      }
      if (lastLoginTime_ != null) {
        output.writeMessage(6, getLastLoginTime());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
      }
      if (status_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, status_);
      }
      for (int i = 0; i < depts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, depts_.get(i));
      }
      if (lastLoginTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getLastLoginTime());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.aaric.achieve.protobuf.UserProto.User)) {
        return super.equals(obj);
      }
      com.github.aaric.achieve.protobuf.UserProto.User other = (com.github.aaric.achieve.protobuf.UserProto.User) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && (getStatus()
          == other.getStatus());
      result = result && getDeptsList()
          .equals(other.getDeptsList());
      result = result && (hasLastLoginTime() == other.hasLastLoginTime());
      if (hasLastLoginTime()) {
        result = result && getLastLoginTime()
            .equals(other.getLastLoginTime());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStatus());
      if (getDeptsCount() > 0) {
        hash = (37 * hash) + DEPTS_FIELD_NUMBER;
        hash = (53 * hash) + getDeptsList().hashCode();
      }
      if (hasLastLoginTime()) {
        hash = (37 * hash) + LASTLOGINTIME_FIELD_NUMBER;
        hash = (53 * hash) + getLastLoginTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.aaric.achieve.protobuf.UserProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aaric.achieve.protobuf.UserProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aaric.achieve.protobuf.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aaric.achieve.protobuf.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aaric.achieve.protobuf.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.aaric.achieve.protobuf.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.aaric.achieve.protobuf.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aaric.achieve.protobuf.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aaric.achieve.protobuf.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.aaric.achieve.protobuf.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.aaric.achieve.protobuf.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.aaric.achieve.protobuf.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.aaric.achieve.protobuf.UserProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.User)
        com.github.aaric.achieve.protobuf.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.aaric.achieve.protobuf.UserProto.internal_static_protobuf_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.aaric.achieve.protobuf.UserProto.internal_static_protobuf_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.aaric.achieve.protobuf.UserProto.User.class, com.github.aaric.achieve.protobuf.UserProto.User.Builder.class);
      }

      // Construct using com.github.aaric.achieve.protobuf.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDeptsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        username_ = "";

        password_ = "";

        status_ = false;

        if (deptsBuilder_ == null) {
          depts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          deptsBuilder_.clear();
        }
        if (lastLoginTimeBuilder_ == null) {
          lastLoginTime_ = null;
        } else {
          lastLoginTime_ = null;
          lastLoginTimeBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.aaric.achieve.protobuf.UserProto.internal_static_protobuf_User_descriptor;
      }

      public com.github.aaric.achieve.protobuf.UserProto.User getDefaultInstanceForType() {
        return com.github.aaric.achieve.protobuf.UserProto.User.getDefaultInstance();
      }

      public com.github.aaric.achieve.protobuf.UserProto.User build() {
        com.github.aaric.achieve.protobuf.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.aaric.achieve.protobuf.UserProto.User buildPartial() {
        com.github.aaric.achieve.protobuf.UserProto.User result = new com.github.aaric.achieve.protobuf.UserProto.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.username_ = username_;
        result.password_ = password_;
        result.status_ = status_;
        if (deptsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            depts_ = java.util.Collections.unmodifiableList(depts_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.depts_ = depts_;
        } else {
          result.depts_ = deptsBuilder_.build();
        }
        if (lastLoginTimeBuilder_ == null) {
          result.lastLoginTime_ = lastLoginTime_;
        } else {
          result.lastLoginTime_ = lastLoginTimeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.aaric.achieve.protobuf.UserProto.User) {
          return mergeFrom((com.github.aaric.achieve.protobuf.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.aaric.achieve.protobuf.UserProto.User other) {
        if (other == com.github.aaric.achieve.protobuf.UserProto.User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (other.getStatus() != false) {
          setStatus(other.getStatus());
        }
        if (deptsBuilder_ == null) {
          if (!other.depts_.isEmpty()) {
            if (depts_.isEmpty()) {
              depts_ = other.depts_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureDeptsIsMutable();
              depts_.addAll(other.depts_);
            }
            onChanged();
          }
        } else {
          if (!other.depts_.isEmpty()) {
            if (deptsBuilder_.isEmpty()) {
              deptsBuilder_.dispose();
              deptsBuilder_ = null;
              depts_ = other.depts_;
              bitField0_ = (bitField0_ & ~0x00000010);
              deptsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDeptsFieldBuilder() : null;
            } else {
              deptsBuilder_.addAllMessages(other.depts_);
            }
          }
        }
        if (other.hasLastLoginTime()) {
          mergeLastLoginTime(other.getLastLoginTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.aaric.achieve.protobuf.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.aaric.achieve.protobuf.UserProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private boolean status_ ;
      /**
       * <code>bool status = 4;</code>
       */
      public boolean getStatus() {
        return status_;
      }
      /**
       * <code>bool status = 4;</code>
       */
      public Builder setStatus(boolean value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = false;
        onChanged();
        return this;
      }

      private java.util.List<com.github.aaric.achieve.protobuf.DeptProto.Dept> depts_ =
        java.util.Collections.emptyList();
      private void ensureDeptsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          depts_ = new java.util.ArrayList<com.github.aaric.achieve.protobuf.DeptProto.Dept>(depts_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.aaric.achieve.protobuf.DeptProto.Dept, com.github.aaric.achieve.protobuf.DeptProto.Dept.Builder, com.github.aaric.achieve.protobuf.DeptProto.DeptOrBuilder> deptsBuilder_;

      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public java.util.List<com.github.aaric.achieve.protobuf.DeptProto.Dept> getDeptsList() {
        if (deptsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(depts_);
        } else {
          return deptsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public int getDeptsCount() {
        if (deptsBuilder_ == null) {
          return depts_.size();
        } else {
          return deptsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public com.github.aaric.achieve.protobuf.DeptProto.Dept getDepts(int index) {
        if (deptsBuilder_ == null) {
          return depts_.get(index);
        } else {
          return deptsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public Builder setDepts(
          int index, com.github.aaric.achieve.protobuf.DeptProto.Dept value) {
        if (deptsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptsIsMutable();
          depts_.set(index, value);
          onChanged();
        } else {
          deptsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public Builder setDepts(
          int index, com.github.aaric.achieve.protobuf.DeptProto.Dept.Builder builderForValue) {
        if (deptsBuilder_ == null) {
          ensureDeptsIsMutable();
          depts_.set(index, builderForValue.build());
          onChanged();
        } else {
          deptsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public Builder addDepts(com.github.aaric.achieve.protobuf.DeptProto.Dept value) {
        if (deptsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptsIsMutable();
          depts_.add(value);
          onChanged();
        } else {
          deptsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public Builder addDepts(
          int index, com.github.aaric.achieve.protobuf.DeptProto.Dept value) {
        if (deptsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeptsIsMutable();
          depts_.add(index, value);
          onChanged();
        } else {
          deptsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public Builder addDepts(
          com.github.aaric.achieve.protobuf.DeptProto.Dept.Builder builderForValue) {
        if (deptsBuilder_ == null) {
          ensureDeptsIsMutable();
          depts_.add(builderForValue.build());
          onChanged();
        } else {
          deptsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public Builder addDepts(
          int index, com.github.aaric.achieve.protobuf.DeptProto.Dept.Builder builderForValue) {
        if (deptsBuilder_ == null) {
          ensureDeptsIsMutable();
          depts_.add(index, builderForValue.build());
          onChanged();
        } else {
          deptsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public Builder addAllDepts(
          java.lang.Iterable<? extends com.github.aaric.achieve.protobuf.DeptProto.Dept> values) {
        if (deptsBuilder_ == null) {
          ensureDeptsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, depts_);
          onChanged();
        } else {
          deptsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public Builder clearDepts() {
        if (deptsBuilder_ == null) {
          depts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          deptsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public Builder removeDepts(int index) {
        if (deptsBuilder_ == null) {
          ensureDeptsIsMutable();
          depts_.remove(index);
          onChanged();
        } else {
          deptsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public com.github.aaric.achieve.protobuf.DeptProto.Dept.Builder getDeptsBuilder(
          int index) {
        return getDeptsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public com.github.aaric.achieve.protobuf.DeptProto.DeptOrBuilder getDeptsOrBuilder(
          int index) {
        if (deptsBuilder_ == null) {
          return depts_.get(index);  } else {
          return deptsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public java.util.List<? extends com.github.aaric.achieve.protobuf.DeptProto.DeptOrBuilder> 
           getDeptsOrBuilderList() {
        if (deptsBuilder_ != null) {
          return deptsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(depts_);
        }
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public com.github.aaric.achieve.protobuf.DeptProto.Dept.Builder addDeptsBuilder() {
        return getDeptsFieldBuilder().addBuilder(
            com.github.aaric.achieve.protobuf.DeptProto.Dept.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public com.github.aaric.achieve.protobuf.DeptProto.Dept.Builder addDeptsBuilder(
          int index) {
        return getDeptsFieldBuilder().addBuilder(
            index, com.github.aaric.achieve.protobuf.DeptProto.Dept.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Dept depts = 5;</code>
       */
      public java.util.List<com.github.aaric.achieve.protobuf.DeptProto.Dept.Builder> 
           getDeptsBuilderList() {
        return getDeptsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.aaric.achieve.protobuf.DeptProto.Dept, com.github.aaric.achieve.protobuf.DeptProto.Dept.Builder, com.github.aaric.achieve.protobuf.DeptProto.DeptOrBuilder> 
          getDeptsFieldBuilder() {
        if (deptsBuilder_ == null) {
          deptsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.aaric.achieve.protobuf.DeptProto.Dept, com.github.aaric.achieve.protobuf.DeptProto.Dept.Builder, com.github.aaric.achieve.protobuf.DeptProto.DeptOrBuilder>(
                  depts_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          depts_ = null;
        }
        return deptsBuilder_;
      }

      private com.google.protobuf.Timestamp lastLoginTime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastLoginTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
       */
      public boolean hasLastLoginTime() {
        return lastLoginTimeBuilder_ != null || lastLoginTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
       */
      public com.google.protobuf.Timestamp getLastLoginTime() {
        if (lastLoginTimeBuilder_ == null) {
          return lastLoginTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastLoginTime_;
        } else {
          return lastLoginTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
       */
      public Builder setLastLoginTime(com.google.protobuf.Timestamp value) {
        if (lastLoginTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lastLoginTime_ = value;
          onChanged();
        } else {
          lastLoginTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
       */
      public Builder setLastLoginTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (lastLoginTimeBuilder_ == null) {
          lastLoginTime_ = builderForValue.build();
          onChanged();
        } else {
          lastLoginTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
       */
      public Builder mergeLastLoginTime(com.google.protobuf.Timestamp value) {
        if (lastLoginTimeBuilder_ == null) {
          if (lastLoginTime_ != null) {
            lastLoginTime_ =
              com.google.protobuf.Timestamp.newBuilder(lastLoginTime_).mergeFrom(value).buildPartial();
          } else {
            lastLoginTime_ = value;
          }
          onChanged();
        } else {
          lastLoginTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
       */
      public Builder clearLastLoginTime() {
        if (lastLoginTimeBuilder_ == null) {
          lastLoginTime_ = null;
          onChanged();
        } else {
          lastLoginTime_ = null;
          lastLoginTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getLastLoginTimeBuilder() {
        
        onChanged();
        return getLastLoginTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getLastLoginTimeOrBuilder() {
        if (lastLoginTimeBuilder_ != null) {
          return lastLoginTimeBuilder_.getMessageOrBuilder();
        } else {
          return lastLoginTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : lastLoginTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp lastLoginTime = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getLastLoginTimeFieldBuilder() {
        if (lastLoginTimeBuilder_ == null) {
          lastLoginTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getLastLoginTime(),
                  getParentForChildren(),
                  isClean());
          lastLoginTime_ = null;
        }
        return lastLoginTimeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.User)
    }

    // @@protoc_insertion_point(class_scope:protobuf.User)
    private static final com.github.aaric.achieve.protobuf.UserProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.aaric.achieve.protobuf.UserProto.User();
    }

    public static com.github.aaric.achieve.protobuf.UserProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.github.aaric.achieve.protobuf.UserProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\010protobuf\032\037google/protobuf/" +
      "timestamp.proto\032\nDept.proto\"\230\001\n\004User\022\n\n\002" +
      "id\030\001 \001(\005\022\020\n\010username\030\002 \001(\t\022\020\n\010password\030\003" +
      " \001(\t\022\016\n\006status\030\004 \001(\010\022\035\n\005depts\030\005 \003(\0132\016.pr" +
      "otobuf.Dept\0221\n\rlastLoginTime\030\006 \001(\0132\032.goo" +
      "gle.protobuf.TimestampB.\n!com.github.aar" +
      "ic.achieve.protobufB\tUserProtoP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.github.aaric.achieve.protobuf.DeptProto.getDescriptor(),
        }, assigner);
    internal_static_protobuf_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_User_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "Status", "Depts", "LastLoginTime", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.github.aaric.achieve.protobuf.DeptProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
